// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test.proto

#ifndef PROTOBUF_test_2eproto__INCLUDED
#define PROTOBUF_test_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
// @@protoc_insertion_point(includes)

namespace pb {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_test_2eproto();
void protobuf_AssignDesc_test_2eproto();
void protobuf_ShutdownFile_test_2eproto();

class ResultFormatCBanerPb;
class ResultFormatCBanerPb_Meta;
class ResultFormatCBanerPb_Doc;

// ===================================================================

class ResultFormatCBanerPb_Meta : public ::google::protobuf::Message {
 public:
  ResultFormatCBanerPb_Meta();
  virtual ~ResultFormatCBanerPb_Meta();
  
  ResultFormatCBanerPb_Meta(const ResultFormatCBanerPb_Meta& from);
  
  inline ResultFormatCBanerPb_Meta& operator=(const ResultFormatCBanerPb_Meta& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const ResultFormatCBanerPb_Meta& default_instance();
  
  void Swap(ResultFormatCBanerPb_Meta* other);
  
  // implements Message ----------------------------------------------
  
  ResultFormatCBanerPb_Meta* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ResultFormatCBanerPb_Meta& from);
  void MergeFrom(const ResultFormatCBanerPb_Meta& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional int32 searched = 1;
  inline bool has_searched() const;
  inline void clear_searched();
  static const int kSearchedFieldNumber = 1;
  inline ::google::protobuf::int32 searched() const;
  inline void set_searched(::google::protobuf::int32 value);
  
  // optional int32 returned = 2;
  inline bool has_returned() const;
  inline void clear_returned();
  static const int kReturnedFieldNumber = 2;
  inline ::google::protobuf::int32 returned() const;
  inline void set_returned(::google::protobuf::int32 value);
  
  // optional int32 found = 3;
  inline bool has_found() const;
  inline void clear_found();
  static const int kFoundFieldNumber = 3;
  inline ::google::protobuf::int32 found() const;
  inline void set_found(::google::protobuf::int32 value);
  
  // optional int32 restrict = 4;
  inline bool has_restrict() const;
  inline void clear_restrict();
  static const int kRestrictFieldNumber = 4;
  inline ::google::protobuf::int32 restrict() const;
  inline void set_restrict(::google::protobuf::int32 value);
  
  // optional int32 prevpage = 5;
  inline bool has_prevpage() const;
  inline void clear_prevpage();
  static const int kPrevpageFieldNumber = 5;
  inline ::google::protobuf::int32 prevpage() const;
  inline void set_prevpage(::google::protobuf::int32 value);
  
  // optional int32 nextpage = 6;
  inline bool has_nextpage() const;
  inline void clear_nextpage();
  static const int kNextpageFieldNumber = 6;
  inline ::google::protobuf::int32 nextpage() const;
  inline void set_nextpage(::google::protobuf::int32 value);
  
  // optional int32 time = 7;
  inline bool has_time() const;
  inline void clear_time();
  static const int kTimeFieldNumber = 7;
  inline ::google::protobuf::int32 time() const;
  inline void set_time(::google::protobuf::int32 value);
  
  // @@protoc_insertion_point(class_scope:pb.ResultFormatCBanerPb.Meta)
 private:
  inline void set_has_searched();
  inline void clear_has_searched();
  inline void set_has_returned();
  inline void clear_has_returned();
  inline void set_has_found();
  inline void clear_has_found();
  inline void set_has_restrict();
  inline void clear_has_restrict();
  inline void set_has_prevpage();
  inline void clear_has_prevpage();
  inline void set_has_nextpage();
  inline void clear_has_nextpage();
  inline void set_has_time();
  inline void clear_has_time();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::int32 searched_;
  ::google::protobuf::int32 returned_;
  ::google::protobuf::int32 found_;
  ::google::protobuf::int32 restrict_;
  ::google::protobuf::int32 prevpage_;
  ::google::protobuf::int32 nextpage_;
  ::google::protobuf::int32 time_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(7 + 31) / 32];
  
  friend void  protobuf_AddDesc_test_2eproto();
  friend void protobuf_AssignDesc_test_2eproto();
  friend void protobuf_ShutdownFile_test_2eproto();
  
  void InitAsDefaultInstance();
  static ResultFormatCBanerPb_Meta* default_instance_;
};
// -------------------------------------------------------------------

class ResultFormatCBanerPb_Doc : public ::google::protobuf::Message {
 public:
  ResultFormatCBanerPb_Doc();
  virtual ~ResultFormatCBanerPb_Doc();
  
  ResultFormatCBanerPb_Doc(const ResultFormatCBanerPb_Doc& from);
  
  inline ResultFormatCBanerPb_Doc& operator=(const ResultFormatCBanerPb_Doc& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const ResultFormatCBanerPb_Doc& default_instance();
  
  void Swap(ResultFormatCBanerPb_Doc* other);
  
  // implements Message ----------------------------------------------
  
  ResultFormatCBanerPb_Doc* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ResultFormatCBanerPb_Doc& from);
  void MergeFrom(const ResultFormatCBanerPb_Doc& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional bytes bid_adid = 1;
  inline bool has_bid_adid() const;
  inline void clear_bid_adid();
  static const int kBidAdidFieldNumber = 1;
  inline const ::std::string& bid_adid() const;
  inline void set_bid_adid(const ::std::string& value);
  inline void set_bid_adid(const char* value);
  inline void set_bid_adid(const void* value, size_t size);
  inline ::std::string* mutable_bid_adid();
  inline ::std::string* release_bid_adid();
  
  // @@protoc_insertion_point(class_scope:pb.ResultFormatCBanerPb.Doc)
 private:
  inline void set_has_bid_adid();
  inline void clear_has_bid_adid();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::std::string* bid_adid_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];
  
  friend void  protobuf_AddDesc_test_2eproto();
  friend void protobuf_AssignDesc_test_2eproto();
  friend void protobuf_ShutdownFile_test_2eproto();
  
  void InitAsDefaultInstance();
  static ResultFormatCBanerPb_Doc* default_instance_;
};
// -------------------------------------------------------------------

class ResultFormatCBanerPb : public ::google::protobuf::Message {
 public:
  ResultFormatCBanerPb();
  virtual ~ResultFormatCBanerPb();
  
  ResultFormatCBanerPb(const ResultFormatCBanerPb& from);
  
  inline ResultFormatCBanerPb& operator=(const ResultFormatCBanerPb& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const ResultFormatCBanerPb& default_instance();
  
  void Swap(ResultFormatCBanerPb* other);
  
  // implements Message ----------------------------------------------
  
  ResultFormatCBanerPb* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ResultFormatCBanerPb& from);
  void MergeFrom(const ResultFormatCBanerPb& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  typedef ResultFormatCBanerPb_Meta Meta;
  typedef ResultFormatCBanerPb_Doc Doc;
  
  // accessors -------------------------------------------------------
  
  // optional .pb.ResultFormatCBanerPb.Meta meta = 1;
  inline bool has_meta() const;
  inline void clear_meta();
  static const int kMetaFieldNumber = 1;
  inline const ::pb::ResultFormatCBanerPb_Meta& meta() const;
  inline ::pb::ResultFormatCBanerPb_Meta* mutable_meta();
  inline ::pb::ResultFormatCBanerPb_Meta* release_meta();
  
  // repeated .pb.ResultFormatCBanerPb.Doc docs = 2;
  inline int docs_size() const;
  inline void clear_docs();
  static const int kDocsFieldNumber = 2;
  inline const ::pb::ResultFormatCBanerPb_Doc& docs(int index) const;
  inline ::pb::ResultFormatCBanerPb_Doc* mutable_docs(int index);
  inline ::pb::ResultFormatCBanerPb_Doc* add_docs();
  inline const ::google::protobuf::RepeatedPtrField< ::pb::ResultFormatCBanerPb_Doc >&
      docs() const;
  inline ::google::protobuf::RepeatedPtrField< ::pb::ResultFormatCBanerPb_Doc >*
      mutable_docs();
  
  // optional int32 code = 3;
  inline bool has_code() const;
  inline void clear_code();
  static const int kCodeFieldNumber = 3;
  inline ::google::protobuf::int32 code() const;
  inline void set_code(::google::protobuf::int32 value);
  
  // optional bytes msg = 4;
  inline bool has_msg() const;
  inline void clear_msg();
  static const int kMsgFieldNumber = 4;
  inline const ::std::string& msg() const;
  inline void set_msg(const ::std::string& value);
  inline void set_msg(const char* value);
  inline void set_msg(const void* value, size_t size);
  inline ::std::string* mutable_msg();
  inline ::std::string* release_msg();
  
  // optional bytes msg2 = 5;
  inline bool has_msg2() const;
  inline void clear_msg2();
  static const int kMsg2FieldNumber = 5;
  inline const ::std::string& msg2() const;
  inline void set_msg2(const ::std::string& value);
  inline void set_msg2(const char* value);
  inline void set_msg2(const void* value, size_t size);
  inline ::std::string* mutable_msg2();
  inline ::std::string* release_msg2();
  
  // @@protoc_insertion_point(class_scope:pb.ResultFormatCBanerPb)
 private:
  inline void set_has_meta();
  inline void clear_has_meta();
  inline void set_has_code();
  inline void clear_has_code();
  inline void set_has_msg();
  inline void clear_has_msg();
  inline void set_has_msg2();
  inline void clear_has_msg2();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::pb::ResultFormatCBanerPb_Meta* meta_;
  ::google::protobuf::RepeatedPtrField< ::pb::ResultFormatCBanerPb_Doc > docs_;
  ::std::string* msg_;
  ::std::string* msg2_;
  ::google::protobuf::int32 code_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(5 + 31) / 32];
  
  friend void  protobuf_AddDesc_test_2eproto();
  friend void protobuf_AssignDesc_test_2eproto();
  friend void protobuf_ShutdownFile_test_2eproto();
  
  void InitAsDefaultInstance();
  static ResultFormatCBanerPb* default_instance_;
};
// ===================================================================


// ===================================================================

// ResultFormatCBanerPb_Meta

// optional int32 searched = 1;
inline bool ResultFormatCBanerPb_Meta::has_searched() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ResultFormatCBanerPb_Meta::set_has_searched() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ResultFormatCBanerPb_Meta::clear_has_searched() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ResultFormatCBanerPb_Meta::clear_searched() {
  searched_ = 0;
  clear_has_searched();
}
inline ::google::protobuf::int32 ResultFormatCBanerPb_Meta::searched() const {
  return searched_;
}
inline void ResultFormatCBanerPb_Meta::set_searched(::google::protobuf::int32 value) {
  set_has_searched();
  searched_ = value;
}

// optional int32 returned = 2;
inline bool ResultFormatCBanerPb_Meta::has_returned() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ResultFormatCBanerPb_Meta::set_has_returned() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ResultFormatCBanerPb_Meta::clear_has_returned() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ResultFormatCBanerPb_Meta::clear_returned() {
  returned_ = 0;
  clear_has_returned();
}
inline ::google::protobuf::int32 ResultFormatCBanerPb_Meta::returned() const {
  return returned_;
}
inline void ResultFormatCBanerPb_Meta::set_returned(::google::protobuf::int32 value) {
  set_has_returned();
  returned_ = value;
}

// optional int32 found = 3;
inline bool ResultFormatCBanerPb_Meta::has_found() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void ResultFormatCBanerPb_Meta::set_has_found() {
  _has_bits_[0] |= 0x00000004u;
}
inline void ResultFormatCBanerPb_Meta::clear_has_found() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void ResultFormatCBanerPb_Meta::clear_found() {
  found_ = 0;
  clear_has_found();
}
inline ::google::protobuf::int32 ResultFormatCBanerPb_Meta::found() const {
  return found_;
}
inline void ResultFormatCBanerPb_Meta::set_found(::google::protobuf::int32 value) {
  set_has_found();
  found_ = value;
}

// optional int32 restrict = 4;
inline bool ResultFormatCBanerPb_Meta::has_restrict() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void ResultFormatCBanerPb_Meta::set_has_restrict() {
  _has_bits_[0] |= 0x00000008u;
}
inline void ResultFormatCBanerPb_Meta::clear_has_restrict() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void ResultFormatCBanerPb_Meta::clear_restrict() {
  restrict_ = 0;
  clear_has_restrict();
}
inline ::google::protobuf::int32 ResultFormatCBanerPb_Meta::restrict() const {
  return restrict_;
}
inline void ResultFormatCBanerPb_Meta::set_restrict(::google::protobuf::int32 value) {
  set_has_restrict();
  restrict_ = value;
}

// optional int32 prevpage = 5;
inline bool ResultFormatCBanerPb_Meta::has_prevpage() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void ResultFormatCBanerPb_Meta::set_has_prevpage() {
  _has_bits_[0] |= 0x00000010u;
}
inline void ResultFormatCBanerPb_Meta::clear_has_prevpage() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void ResultFormatCBanerPb_Meta::clear_prevpage() {
  prevpage_ = 0;
  clear_has_prevpage();
}
inline ::google::protobuf::int32 ResultFormatCBanerPb_Meta::prevpage() const {
  return prevpage_;
}
inline void ResultFormatCBanerPb_Meta::set_prevpage(::google::protobuf::int32 value) {
  set_has_prevpage();
  prevpage_ = value;
}

// optional int32 nextpage = 6;
inline bool ResultFormatCBanerPb_Meta::has_nextpage() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void ResultFormatCBanerPb_Meta::set_has_nextpage() {
  _has_bits_[0] |= 0x00000020u;
}
inline void ResultFormatCBanerPb_Meta::clear_has_nextpage() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void ResultFormatCBanerPb_Meta::clear_nextpage() {
  nextpage_ = 0;
  clear_has_nextpage();
}
inline ::google::protobuf::int32 ResultFormatCBanerPb_Meta::nextpage() const {
  return nextpage_;
}
inline void ResultFormatCBanerPb_Meta::set_nextpage(::google::protobuf::int32 value) {
  set_has_nextpage();
  nextpage_ = value;
}

// optional int32 time = 7;
inline bool ResultFormatCBanerPb_Meta::has_time() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void ResultFormatCBanerPb_Meta::set_has_time() {
  _has_bits_[0] |= 0x00000040u;
}
inline void ResultFormatCBanerPb_Meta::clear_has_time() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void ResultFormatCBanerPb_Meta::clear_time() {
  time_ = 0;
  clear_has_time();
}
inline ::google::protobuf::int32 ResultFormatCBanerPb_Meta::time() const {
  return time_;
}
inline void ResultFormatCBanerPb_Meta::set_time(::google::protobuf::int32 value) {
  set_has_time();
  time_ = value;
}

// -------------------------------------------------------------------

// ResultFormatCBanerPb_Doc

// optional bytes bid_adid = 1;
inline bool ResultFormatCBanerPb_Doc::has_bid_adid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ResultFormatCBanerPb_Doc::set_has_bid_adid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ResultFormatCBanerPb_Doc::clear_has_bid_adid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ResultFormatCBanerPb_Doc::clear_bid_adid() {
  if (bid_adid_ != &::google::protobuf::internal::kEmptyString) {
    bid_adid_->clear();
  }
  clear_has_bid_adid();
}
inline const ::std::string& ResultFormatCBanerPb_Doc::bid_adid() const {
  return *bid_adid_;
}
inline void ResultFormatCBanerPb_Doc::set_bid_adid(const ::std::string& value) {
  set_has_bid_adid();
  if (bid_adid_ == &::google::protobuf::internal::kEmptyString) {
    bid_adid_ = new ::std::string;
  }
  bid_adid_->assign(value);
}
inline void ResultFormatCBanerPb_Doc::set_bid_adid(const char* value) {
  set_has_bid_adid();
  if (bid_adid_ == &::google::protobuf::internal::kEmptyString) {
    bid_adid_ = new ::std::string;
  }
  bid_adid_->assign(value);
}
inline void ResultFormatCBanerPb_Doc::set_bid_adid(const void* value, size_t size) {
  set_has_bid_adid();
  if (bid_adid_ == &::google::protobuf::internal::kEmptyString) {
    bid_adid_ = new ::std::string;
  }
  bid_adid_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* ResultFormatCBanerPb_Doc::mutable_bid_adid() {
  set_has_bid_adid();
  if (bid_adid_ == &::google::protobuf::internal::kEmptyString) {
    bid_adid_ = new ::std::string;
  }
  return bid_adid_;
}
inline ::std::string* ResultFormatCBanerPb_Doc::release_bid_adid() {
  clear_has_bid_adid();
  if (bid_adid_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = bid_adid_;
    bid_adid_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}

// -------------------------------------------------------------------

// ResultFormatCBanerPb

// optional .pb.ResultFormatCBanerPb.Meta meta = 1;
inline bool ResultFormatCBanerPb::has_meta() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ResultFormatCBanerPb::set_has_meta() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ResultFormatCBanerPb::clear_has_meta() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ResultFormatCBanerPb::clear_meta() {
  if (meta_ != NULL) meta_->::pb::ResultFormatCBanerPb_Meta::Clear();
  clear_has_meta();
}
inline const ::pb::ResultFormatCBanerPb_Meta& ResultFormatCBanerPb::meta() const {
  return meta_ != NULL ? *meta_ : *default_instance_->meta_;
}
inline ::pb::ResultFormatCBanerPb_Meta* ResultFormatCBanerPb::mutable_meta() {
  set_has_meta();
  if (meta_ == NULL) meta_ = new ::pb::ResultFormatCBanerPb_Meta;
  return meta_;
}
inline ::pb::ResultFormatCBanerPb_Meta* ResultFormatCBanerPb::release_meta() {
  clear_has_meta();
  ::pb::ResultFormatCBanerPb_Meta* temp = meta_;
  meta_ = NULL;
  return temp;
}

// repeated .pb.ResultFormatCBanerPb.Doc docs = 2;
inline int ResultFormatCBanerPb::docs_size() const {
  return docs_.size();
}
inline void ResultFormatCBanerPb::clear_docs() {
  docs_.Clear();
}
inline const ::pb::ResultFormatCBanerPb_Doc& ResultFormatCBanerPb::docs(int index) const {
  return docs_.Get(index);
}
inline ::pb::ResultFormatCBanerPb_Doc* ResultFormatCBanerPb::mutable_docs(int index) {
  return docs_.Mutable(index);
}
inline ::pb::ResultFormatCBanerPb_Doc* ResultFormatCBanerPb::add_docs() {
  return docs_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::pb::ResultFormatCBanerPb_Doc >&
ResultFormatCBanerPb::docs() const {
  return docs_;
}
inline ::google::protobuf::RepeatedPtrField< ::pb::ResultFormatCBanerPb_Doc >*
ResultFormatCBanerPb::mutable_docs() {
  return &docs_;
}

// optional int32 code = 3;
inline bool ResultFormatCBanerPb::has_code() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void ResultFormatCBanerPb::set_has_code() {
  _has_bits_[0] |= 0x00000004u;
}
inline void ResultFormatCBanerPb::clear_has_code() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void ResultFormatCBanerPb::clear_code() {
  code_ = 0;
  clear_has_code();
}
inline ::google::protobuf::int32 ResultFormatCBanerPb::code() const {
  return code_;
}
inline void ResultFormatCBanerPb::set_code(::google::protobuf::int32 value) {
  set_has_code();
  code_ = value;
}

// optional bytes msg = 4;
inline bool ResultFormatCBanerPb::has_msg() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void ResultFormatCBanerPb::set_has_msg() {
  _has_bits_[0] |= 0x00000008u;
}
inline void ResultFormatCBanerPb::clear_has_msg() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void ResultFormatCBanerPb::clear_msg() {
  if (msg_ != &::google::protobuf::internal::kEmptyString) {
    msg_->clear();
  }
  clear_has_msg();
}
inline const ::std::string& ResultFormatCBanerPb::msg() const {
  return *msg_;
}
inline void ResultFormatCBanerPb::set_msg(const ::std::string& value) {
  set_has_msg();
  if (msg_ == &::google::protobuf::internal::kEmptyString) {
    msg_ = new ::std::string;
  }
  msg_->assign(value);
}
inline void ResultFormatCBanerPb::set_msg(const char* value) {
  set_has_msg();
  if (msg_ == &::google::protobuf::internal::kEmptyString) {
    msg_ = new ::std::string;
  }
  msg_->assign(value);
}
inline void ResultFormatCBanerPb::set_msg(const void* value, size_t size) {
  set_has_msg();
  if (msg_ == &::google::protobuf::internal::kEmptyString) {
    msg_ = new ::std::string;
  }
  msg_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* ResultFormatCBanerPb::mutable_msg() {
  set_has_msg();
  if (msg_ == &::google::protobuf::internal::kEmptyString) {
    msg_ = new ::std::string;
  }
  return msg_;
}
inline ::std::string* ResultFormatCBanerPb::release_msg() {
  clear_has_msg();
  if (msg_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = msg_;
    msg_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}

// optional bytes msg2 = 5;
inline bool ResultFormatCBanerPb::has_msg2() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void ResultFormatCBanerPb::set_has_msg2() {
  _has_bits_[0] |= 0x00000010u;
}
inline void ResultFormatCBanerPb::clear_has_msg2() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void ResultFormatCBanerPb::clear_msg2() {
  if (msg2_ != &::google::protobuf::internal::kEmptyString) {
    msg2_->clear();
  }
  clear_has_msg2();
}
inline const ::std::string& ResultFormatCBanerPb::msg2() const {
  return *msg2_;
}
inline void ResultFormatCBanerPb::set_msg2(const ::std::string& value) {
  set_has_msg2();
  if (msg2_ == &::google::protobuf::internal::kEmptyString) {
    msg2_ = new ::std::string;
  }
  msg2_->assign(value);
}
inline void ResultFormatCBanerPb::set_msg2(const char* value) {
  set_has_msg2();
  if (msg2_ == &::google::protobuf::internal::kEmptyString) {
    msg2_ = new ::std::string;
  }
  msg2_->assign(value);
}
inline void ResultFormatCBanerPb::set_msg2(const void* value, size_t size) {
  set_has_msg2();
  if (msg2_ == &::google::protobuf::internal::kEmptyString) {
    msg2_ = new ::std::string;
  }
  msg2_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* ResultFormatCBanerPb::mutable_msg2() {
  set_has_msg2();
  if (msg2_ == &::google::protobuf::internal::kEmptyString) {
    msg2_ = new ::std::string;
  }
  return msg2_;
}
inline ::std::string* ResultFormatCBanerPb::release_msg2() {
  clear_has_msg2();
  if (msg2_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = msg2_;
    msg2_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace pb

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_test_2eproto__INCLUDED
