# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

# User specific aliases and functions

# added by Anaconda3 installer
. /home/lianjiang.yulj/anaconda3/etc/profile.d/conda.sh
#export PATH="/home/lianjiang.yulj/anaconda3/bin:$PATH"
conda activate
