# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
    . ~/.bashrc
fi

# User specific environment and startup programs

PATH=$PATH:$HOME/.local/bin:$HOME/bin

export PATH

# User specific environment and startup programs
export JAVA_HOME=/opt/taobao/install/ajdk-8.5.9_fp1-b2
export WORK_HOME=/home/lianjiang.yulj/workspace.github
export GCC_HOME=$WORK_HOME/cxx_standard_tools/gcc/
export GDB_HOME=$WORK_HOME/cxx_standard_tools/gdb/
export CLANG_ROOT=$WORK_HOME/cxx_standard_tools/clang/clang/

#找到动态库的路径
export LD_LIBRARY_PATH=$GCC_HOME/lib64:$GCC_HOME/lib/gcc/x86_64-pc-linux-gnu/8.1.0/:$GCC_HOME/lib/gcc/x86_64-pc-linux-gnu/8.1.0/plugin:$GDB_HOME/usr/lib:/usr/local/lib64:/usr/local/lib:$LD_LIBRARY_PATH
#找到静态库的路径
export LIBRARY_PATH=$LD_LIBRARY_PATH:$LIBRARY_PATH

export CPLUS_INCLUDE_PATH=$GCC_HOME/include/c++/8.1.0:$GCC_HOME/include/c++/8.1.0/x86_64-pc-linux-gnu/:$CPLUS_INCLUDE_PATH
export C_INCLUDE_PATH=$CPLUS_INCLUDE_PATH:$C_INCLUDE_PATH
export OBJCPLUS_INCLUDE_PATH=$LIBRARY_PATH:$CPLUS_INCLUDE_PATH:$OBJCPLUS_INCLUDE_PATH
export OBJC_INCLUDE_PATH=$OBJCPLUS_INCLUDE_PATH:$OBJC_INCLUDE_PATH

export PATH=$GCC_HOME/bin:$GDB_HOME/usr/bin:$CLANG_ROOT/bin:$JAVA_HOME/bin:/usr/local/bin:$PATH
#export PYTHONPATH=/usr/lib/python2.7/site-packages/:/usr/lib64/python2.7/site-packages/:$PYTHONPATH

export BAZEL_ROOT=$WORK_HOME/opensource/bazel_tutorial/bazel/
export PATH=$BAZEL_ROOT/output/:$PATH

#/usr/local/bin/keychain ~/.ssh/id_dsa > /dev/null
#eval `/usr/local/bin/keychain --eval id_dsa`

#for go environment
if [ -f ~/.profile ]; then
    . ~/.profile
fi

export LANG=en_US.UTF-8

ulimit -c unlimited

alias grep='grep --color=always'

#read -t 10 -p "Display all agent_group? [y/N] " answer
answer=y
case $answer in 
    Y|y) 

        for i in my-offline-dev icbu-search-dev
        do
            #		echo "armorygroup ->>>> $i"
            #		armory -g $i -l
            continue
        done ;;
    N|n) 
        echo "";; 
    *) 
        echo "";; 
esac

alias gm='git merge'
alias gd='git diff'
alias gb='git branch'
alias gl='git lg'
alias gs='git status'
alias ga='git add'
alias gc='git commit'
alias gci='git commit'
alias gco='git checkout'
alias gclone='git clone --recursive'
alias gpush='git push origin'
alias gpull='git pull origin'
alias dpull='sudo docker pull'
alias dpush='sudo docker push'
alias ha3_env='sudo docker exec -u lianjiang.yulj -it lianjiang.yulj.ha3 /bin/bash'
alias dev_env='sudo docker exec -it lianjiang.yulj.env /bin/bash'

test -e "${HOME}/.iterm2_shell_integration.bash" && source "${HOME}/.iterm2_shell_integration.bash"

